### ISSUE TITLE
Trung - Assessment #2

### ISSUE THREAD

**Issue by longhypepoly** [hypepoly-internship-2022/quoc-trung-assessment-2#1]

**Comment by longhypepoly** [comment]
Em sửa lại 1 chút nhé. Hiện tại anh di chuyển chuột nhanh 1 chút thôi thì cube nó đã không theo kịp rồi mặc dù anh chưa nhả chuột.

https://user-images.githubusercontent.com/116874636/203260784-9b941657-7cbb-4e1d-bf5f-8c7ae138f74c.mp4

Với lại em move toàn bộ folder và file ở trong `assessment-2` ra ngoài root folder đi. Sử dụng file git này: https://gist.github.com/longhypepoly/85e226869551b19dc713fdb0afc62a08
Sau này tất cả folder đều phải ở ngoài root folder nhé 😉

**Comment by quoctrungvu1610** [comment]
dạ anh Long

**Comment by longhypepoly** [comment]
Good job 💯
